lists/urls.py
urlpatterns = [
    url(r'^new$', views.new_list, name='new_list'),
    url(r'^(\d+)/$', views.view_list, name='view_list'),
]

superlists/urls.py
from django.conf.urls import url

from lists import views

urlpatterns = [
    url(r'^$', views.home_page, name='home'),
    url(r'^lists/new$', views.new_list, name='new_list'),
    url(r'^lists/(\d+)/$', views.view_list, name='view_list'),
    # url(r'^admin/', include(admin.site.urls)),
]

lists/models.py
from django.db import models
from django.core.urlresolvers import reverse

class List(models.Model):
    def get_absolute_url(self):
        return reverse('view_list', args=[self.id])

class Item(models.Model):
    text = models.TextField(default='')
    list = models.ForeignKey(List, default=None)

lists/views.py
from django.shortcuts import redirect, render
from lists.models import Item, List
from django.core.exceptions import ValidationError

def home_page(request):

    items = Item.objects.all()
    message = 'Yey, waktunya berlibur'
    return render(request, 'home.html',  {'message': message})
def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    items = Item.objects.filter(list=list_)
    count = items.count()
    message = ''
    if count == 0 :
        message = "Yey, waktunya berlibur"
    if count >0 & count <5:
        message = "Sibuk tapi santai"
    if count >=5 :
        message = "Oh Tidak"
    return render(request, 'list.html', {'list': list_,'message': message})

def new_list(request):
    list_ = List.objects.create()
    item = Item(text=request.POST['item_text'], list=list_)
    try:
        item.full_clean()
        item.save()
    except ValidationError:
        list_.delete()
        error = "You can't have an empty list item"
        return render(request, 'home.html', {"error": error})
    return redirect(list_)

def view_list(request, list_id):
    list_ = List.objects.get(id=list_id)
    error = None

    if request.method == 'POST':
        try:
            item = Item(text=request.POST['item_text'], list=list_)
            item.full_clean()
            item.save()
            return redirect(list_)
        except ValidationError:
            error = "You can't have an empty list item"

    return render(request, 'list.html', {'list': list_, 'error': error})

lists/templates/base.html
<!DOCTYPE HTML>
<!--
    Spatial by TEMPLATED
    templated.co @templatedco
    Released for free under the Creative Commons Attribution 3.0 license (templated.co/license)
-->
<html>
    <head>
        <title>Welcome to My Blog!</title>
        <meta http-equiv="content-type" content="text/html; charset=utf-8" />
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <!--[if lte IE 8]><script src="js/html5shiv.js"></script><![endif]-->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="/static/bootstrap/css/bootstrap.min.css" rel="stylesheet">
        <link href="/static/css/skel.css" rel="stylesheet">
        <link href="/static/css/base.css" rel="stylesheet">
        <link href="/static/css/style.css" rel="stylesheet">
        <link href="/static/css/style-xlarge.css" rel="stylesheet">
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script>
        $(function() {
          $('a[href*=#]:not([href=#])').click(function() {
            if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {

              var target = $(this.hash);
              target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
              if (target.length) {
                $('html5shivml,body').animate({
                  scrollTop: target.offset().top
                }, "1px");
                return false;
              }
            }
          });
        });
    </script>
    </head>
    <body class="landing">

        <!-- Header -->
            <header id="header" class="alt">
                <h1><strong><a href="#">Yoga</a></strong> Widyakrisna</h1>
                <nav id="nav">
                    <ul>
                        <li><a href="#">Home</a></li>
                        <li><a href="#one">To Do Lists!</a></li>
                    </ul>
                </nav>
            </header>

        <!-- Banner -->
            <section id="banner">
                <h2>Welcome to My Blog!</h2>
                <p>Disini anda akan melihat tugas Penjaminan Mutu Perangkat Lunak.<br>
                </p>
                <ul class="actions">
                    <li><a href="#one" class="button special big">Yuk Mulai</a></li>
                </ul>
            </section>
            <!-- One -->
                <section id="one" class="wrapper style1">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6 col-md-offset-3 jumbotron">
                                <div class="text-center" id="id_header">
                                    <h1>{% block header_text %}{% endblock %}</h1>
                                    <form method="POST" action="{% block form_action %}{% endblock %}">
                                        <input name="item_text" id="id_new_item"
                                               class="form-control input-lg"
                                               placeholder="Enter a to-do item"
                                        />
                                        {% csrf_token %}
                                        {% if error %}
                                            <div class="form-group has-error">
                                                <span class="help-block">{{ error }}</span>
                                            </div>
                                        {% endif %}
                                    </form>

                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6 col-md-offset-3">
                                {% block table %}
                                {% endblock %}
                            </div>
                        </div>

                    </div>
                    <div class="text-center">
                    <h3> Ini Komentar Pribadi Otomatis : "{{ message }}"</h3>
                    </div>

<!--                    <div class="container 75%">
                        <div class="row 200%">
                            <div class="6u 12u$(medium)">
                                <header class="major">
                                    <h2>Maecenas luctus lectus</h2>
                                    <p>Perspiciatis doloremque recusandae dolor</p>
                                </header>
                            </div>
                            <div class="6u$ 12u$(medium)">
                                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Non ea mollitia corporis id, distinctio sunt veritatis officiis dolore reprehenderit deleniti voluptatibus harum magna, doloremque alias quisquam minus, eaque. Feugiat quod, nesciunt! Iste quos ipsam, iusto sit esse.</p>
                                <p>Dolorum aspernatur maxime libero ratione quidem distinctio, placeat fugiat laborum voluptatum enim neque soluta vel sunt id ex veritatis. Labore rerum, odit sapiente, alias mollitia magnam exercitationem modi amet earum quia atque ipsum voluptas asperiores quas laboriosam.</p>
                            </div>
                        </div>
                    </div> -->
                </section>
        <!-- Footer -->
            <footer id="footer">
                <div class="container">
                    <ul class="copyright">
                        <li>&copy; pmpl7yoga</li>
                        <li>Design: <a href="http://templated.co">TEMPLATED</a></li>
                        <li>Images: <a href="http://unsplash.com">Unsplash</a></li>
                    </ul>
                </div>
            </footer>

    </body>
</html>

lists/templates/home.html
 <html>
    <head>
        <title>Welcome to My Blog</title>
    </head>
    <body>
         {% extends 'base.html' %}
         {% block header_text %}To-Do list{% endblock %}
         {% block form_action %}{% url 'new_list' %}{% endblock %}
        <table id="id_list_table">
        	    {% for item in items %}
      				<tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
    			{% endfor %}
        </table>
        <h3> Ini Komentar Pribadi Otomatis : "{{ message }}"</h3>
   </body>
 </html>

lists/templates/list.html
 <html>
    <head>
        <title>To-Do lists</title>
    </head>
    <body>
    {% extends 'base.html' %}

    {% block header_text %}your To-Do list{% endblock %}

    {% block form_action %}{% url 'view_list' list.id %}{% endblock %}

    {% block table %}
        <table id="id_list_table" class="table">
            {% for item in list.item_set.all %}
                <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
            {% endfor %}
        </table>
    {% endblock %}
        <h3> Ini Komentar Pribadi Otomatis : "{{ message }}"</h3>
    </body>
</html> 